### ISSUE TITLE
cannot list all namespaces in the cluster

### ISSUE THREAD

**Issue by aamattos** [gocd/kubernetes-elastic-agents#68] opened 2018-11-21 15:18 UTC
When trying to configure the plugin I get this error:

io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://mycluster:8443/api/v1/namespaces . Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:myelasticagentsproject:myuseraccount" cannot list namespaces at the cluster scope: User "system:serviceaccount: myelasticagentsproject: myuseraccount" cannot list all namespaces in the cluster.

Is it a requirement for the service account to have access to all namespace in the target cluster ?
I'm trying to configure the plugin targeting a shared cluster where I do not have a sa with cluster reader access.

**Comment by sheroy** [comment] 2018-12-14 17:42
The root cause is identified by this exception in the plugin logs:

2018-12-14 17:38:30,369 ERROR [qtp809762318-29] KubernetesPlugin:128 - Failed validation of plugin settings. The reasons could be - Cluster Url is configured incorrectly or the service
account token might not have enough permissions to list namespaces or incorrect CA certificate.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.55.240.1/api/v1/namespaces. Message: Forbidden!Configured service account doesn't have acce
ss. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:testing:test" cannot list namespaces at the cluster scope.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:407)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:327)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:605)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:70)
	at cd.go.contrib.elasticagent.executors.ValidateConfigurationExecutor.validateNamespaceExistence(ValidateConfigurationExecutor.java:80)
	at cd.go.contrib.elasticagent.executors.ValidateConfigurationExecutor.execute(ValidateConfigurationExecutor.java:71)
	at cd.go.contrib.elasticagent.KubernetesPlugin.handle(KubernetesPlugin.java:67)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:143)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:225)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:202)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:140)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:48)
	at com.thoughtworks.go.plugin.access.common.AbstractExtension.validatePluginSettings(AbstractExtension.java:104)
	at com.thoughtworks.go.server.service.PluginService.validatePluginSettings(PluginService.java:138)
	at com.thoughtworks.go.server.service.PluginService.updatePluginSettingsAndNotifyPluginSettingsChangeListeners(PluginService.java:159)
	at com.thoughtworks.go.server.service.PluginService.updatePluginSettings(PluginService.java:116)

**Comment by arvindsv** [comment] 2018-12-14 18:13
@aamattos - @sheroy and I were wondering whether there is some other way to verify whether a namespace is valid, without doing a [list, as is done here](https://github.com/gocd/kubernetes-elastic-agents/blob/37fa9dc6ece7625231515d98e63475982cee8366/src/main/java/cd/go/contrib/elasticagent/executors/ValidateConfigurationExecutor.java#L80). Technically, you're right. There shouldn't be a need to have the list namespaces permission.

If it's just used for validation, ideally we should remove that call and the corresponding verb ("list") from the cluster role.

**Comment by sheroy** [comment] 2018-12-14 19:32
@aamattos, yes. As @arvindsv said, we're looking into it and the stack trace above was to help us diagnose the issue, not an answer to your question, sorry.

**Comment by sheroy** [comment] 2018-12-14 21:54
@aamattos, @arvindsv and I worked on changing plugin settings validation to use the namespace get API instead of namespace list call. I just created a PR with this change, I'll keep you posted once it gets merged.

**Comment by sheroy** [comment] 2018-12-17 18:32
@aamattos, this change has been released in an experimental plugin release here - https://github.com/gocd/kubernetes-elastic-agents/releases/tag/2.0.0-122-exp. 

You can change the Kubernetes elastic agent plugin jar location in your Helm values.yaml to point to this one to test. The GoCD server service account no longer requires the "namespace list" permission. We will update the Helm chart soon with the latest released plugin jar location. 

/cc: @arvindsv

**Comment by aamattos** [comment] 2018-12-18 16:33
Hi @sheroy , I have installed this experimental release (2.0.0-122) and I can confirm that It works great :)
Now I'm able to run elastic agents with a User Account with edit permissions.
Thanks !!!

**Closed** 2022-08-14 06:17 UTC
